pipeline {
    agent any

    tools {
      maven 'maven 3.3.9'
    }

    stages {
        stage('Build') {
            steps {
                echo 'Building..'
                sh 'mvn -f mad/EventsApp/pom.xml compile'
            }
            }

        stage('Test') {
            steps {
                echo 'Testing..'
                sh 'mvn -f mad/EventsApp/pom.xml test'
            }
        }
        stage('Package') {
            steps {
                echo 'Packaging....'
                sh 'mvn -f mad/EventsApp/pom.xml -DskipTests package'
                archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
            }
        }
    }
}
